apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-frontend-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  team: arbeidsgiver
  liveness:
    path: /liveness
  readiness:
    path: /readiness
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: notifikasjoner