/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.nav.arbeidsgiver;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Notifikasjon extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -187153197205515660L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Notifikasjon\",\"namespace\":\"no.nav.arbeidsgiver\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"beskjeder\",\"type\":\"string\"},{\"name\":\"orgnr\",\"type\":\"string\"},{\"name\":\"servicecode\",\"type\":\"string\"},{\"name\":\"serviceedition\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Notifikasjon> ENCODER =
      new BinaryMessageEncoder<Notifikasjon>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Notifikasjon> DECODER =
      new BinaryMessageDecoder<Notifikasjon>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Notifikasjon> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Notifikasjon> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Notifikasjon> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Notifikasjon>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Notifikasjon to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Notifikasjon from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Notifikasjon instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Notifikasjon fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private java.lang.CharSequence beskjeder;
   private java.lang.CharSequence orgnr;
   private java.lang.CharSequence servicecode;
   private java.lang.CharSequence serviceedition;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Notifikasjon() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param beskjeder The new value for beskjeder
   * @param orgnr The new value for orgnr
   * @param servicecode The new value for servicecode
   * @param serviceedition The new value for serviceedition
   */
  public Notifikasjon(java.lang.CharSequence id, java.lang.CharSequence beskjeder, java.lang.CharSequence orgnr, java.lang.CharSequence servicecode, java.lang.CharSequence serviceedition) {
    this.id = id;
    this.beskjeder = beskjeder;
    this.orgnr = orgnr;
    this.servicecode = servicecode;
    this.serviceedition = serviceedition;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return beskjeder;
    case 2: return orgnr;
    case 3: return servicecode;
    case 4: return serviceedition;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: beskjeder = (java.lang.CharSequence)value$; break;
    case 2: orgnr = (java.lang.CharSequence)value$; break;
    case 3: servicecode = (java.lang.CharSequence)value$; break;
    case 4: serviceedition = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'beskjeder' field.
   * @return The value of the 'beskjeder' field.
   */
  public java.lang.CharSequence getBeskjeder() {
    return beskjeder;
  }


  /**
   * Sets the value of the 'beskjeder' field.
   * @param value the value to set.
   */
  public void setBeskjeder(java.lang.CharSequence value) {
    this.beskjeder = value;
  }

  /**
   * Gets the value of the 'orgnr' field.
   * @return The value of the 'orgnr' field.
   */
  public java.lang.CharSequence getOrgnr() {
    return orgnr;
  }


  /**
   * Sets the value of the 'orgnr' field.
   * @param value the value to set.
   */
  public void setOrgnr(java.lang.CharSequence value) {
    this.orgnr = value;
  }

  /**
   * Gets the value of the 'servicecode' field.
   * @return The value of the 'servicecode' field.
   */
  public java.lang.CharSequence getServicecode() {
    return servicecode;
  }


  /**
   * Sets the value of the 'servicecode' field.
   * @param value the value to set.
   */
  public void setServicecode(java.lang.CharSequence value) {
    this.servicecode = value;
  }

  /**
   * Gets the value of the 'serviceedition' field.
   * @return The value of the 'serviceedition' field.
   */
  public java.lang.CharSequence getServiceedition() {
    return serviceedition;
  }


  /**
   * Sets the value of the 'serviceedition' field.
   * @param value the value to set.
   */
  public void setServiceedition(java.lang.CharSequence value) {
    this.serviceedition = value;
  }

  /**
   * Creates a new Notifikasjon RecordBuilder.
   * @return A new Notifikasjon RecordBuilder
   */
  public static no.nav.arbeidsgiver.Notifikasjon.Builder newBuilder() {
    return new no.nav.arbeidsgiver.Notifikasjon.Builder();
  }

  /**
   * Creates a new Notifikasjon RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Notifikasjon RecordBuilder
   */
  public static no.nav.arbeidsgiver.Notifikasjon.Builder newBuilder(no.nav.arbeidsgiver.Notifikasjon.Builder other) {
    if (other == null) {
      return new no.nav.arbeidsgiver.Notifikasjon.Builder();
    } else {
      return new no.nav.arbeidsgiver.Notifikasjon.Builder(other);
    }
  }

  /**
   * Creates a new Notifikasjon RecordBuilder by copying an existing Notifikasjon instance.
   * @param other The existing instance to copy.
   * @return A new Notifikasjon RecordBuilder
   */
  public static no.nav.arbeidsgiver.Notifikasjon.Builder newBuilder(no.nav.arbeidsgiver.Notifikasjon other) {
    if (other == null) {
      return new no.nav.arbeidsgiver.Notifikasjon.Builder();
    } else {
      return new no.nav.arbeidsgiver.Notifikasjon.Builder(other);
    }
  }

  /**
   * RecordBuilder for Notifikasjon instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Notifikasjon>
    implements org.apache.avro.data.RecordBuilder<Notifikasjon> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence beskjeder;
    private java.lang.CharSequence orgnr;
    private java.lang.CharSequence servicecode;
    private java.lang.CharSequence serviceedition;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.nav.arbeidsgiver.Notifikasjon.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.beskjeder)) {
        this.beskjeder = data().deepCopy(fields()[1].schema(), other.beskjeder);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.orgnr)) {
        this.orgnr = data().deepCopy(fields()[2].schema(), other.orgnr);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.servicecode)) {
        this.servicecode = data().deepCopy(fields()[3].schema(), other.servicecode);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.serviceedition)) {
        this.serviceedition = data().deepCopy(fields()[4].schema(), other.serviceedition);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Notifikasjon instance
     * @param other The existing instance to copy.
     */
    private Builder(no.nav.arbeidsgiver.Notifikasjon other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.beskjeder)) {
        this.beskjeder = data().deepCopy(fields()[1].schema(), other.beskjeder);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.orgnr)) {
        this.orgnr = data().deepCopy(fields()[2].schema(), other.orgnr);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.servicecode)) {
        this.servicecode = data().deepCopy(fields()[3].schema(), other.servicecode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.serviceedition)) {
        this.serviceedition = data().deepCopy(fields()[4].schema(), other.serviceedition);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.Notifikasjon.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.Notifikasjon.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'beskjeder' field.
      * @return The value.
      */
    public java.lang.CharSequence getBeskjeder() {
      return beskjeder;
    }


    /**
      * Sets the value of the 'beskjeder' field.
      * @param value The value of 'beskjeder'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.Notifikasjon.Builder setBeskjeder(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.beskjeder = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'beskjeder' field has been set.
      * @return True if the 'beskjeder' field has been set, false otherwise.
      */
    public boolean hasBeskjeder() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'beskjeder' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.Notifikasjon.Builder clearBeskjeder() {
      beskjeder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'orgnr' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrgnr() {
      return orgnr;
    }


    /**
      * Sets the value of the 'orgnr' field.
      * @param value The value of 'orgnr'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.Notifikasjon.Builder setOrgnr(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.orgnr = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'orgnr' field has been set.
      * @return True if the 'orgnr' field has been set, false otherwise.
      */
    public boolean hasOrgnr() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'orgnr' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.Notifikasjon.Builder clearOrgnr() {
      orgnr = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'servicecode' field.
      * @return The value.
      */
    public java.lang.CharSequence getServicecode() {
      return servicecode;
    }


    /**
      * Sets the value of the 'servicecode' field.
      * @param value The value of 'servicecode'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.Notifikasjon.Builder setServicecode(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.servicecode = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'servicecode' field has been set.
      * @return True if the 'servicecode' field has been set, false otherwise.
      */
    public boolean hasServicecode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'servicecode' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.Notifikasjon.Builder clearServicecode() {
      servicecode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'serviceedition' field.
      * @return The value.
      */
    public java.lang.CharSequence getServiceedition() {
      return serviceedition;
    }


    /**
      * Sets the value of the 'serviceedition' field.
      * @param value The value of 'serviceedition'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.Notifikasjon.Builder setServiceedition(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.serviceedition = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'serviceedition' field has been set.
      * @return True if the 'serviceedition' field has been set, false otherwise.
      */
    public boolean hasServiceedition() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'serviceedition' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.Notifikasjon.Builder clearServiceedition() {
      serviceedition = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Notifikasjon build() {
      try {
        Notifikasjon record = new Notifikasjon();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.beskjeder = fieldSetFlags()[1] ? this.beskjeder : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.orgnr = fieldSetFlags()[2] ? this.orgnr : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.servicecode = fieldSetFlags()[3] ? this.servicecode : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.serviceedition = fieldSetFlags()[4] ? this.serviceedition : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Notifikasjon>
    WRITER$ = (org.apache.avro.io.DatumWriter<Notifikasjon>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Notifikasjon>
    READER$ = (org.apache.avro.io.DatumReader<Notifikasjon>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.beskjeder);

    out.writeString(this.orgnr);

    out.writeString(this.servicecode);

    out.writeString(this.serviceedition);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.beskjeder = in.readString(this.beskjeder instanceof Utf8 ? (Utf8)this.beskjeder : null);

      this.orgnr = in.readString(this.orgnr instanceof Utf8 ? (Utf8)this.orgnr : null);

      this.servicecode = in.readString(this.servicecode instanceof Utf8 ? (Utf8)this.servicecode : null);

      this.serviceedition = in.readString(this.serviceedition instanceof Utf8 ? (Utf8)this.serviceedition : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.beskjeder = in.readString(this.beskjeder instanceof Utf8 ? (Utf8)this.beskjeder : null);
          break;

        case 2:
          this.orgnr = in.readString(this.orgnr instanceof Utf8 ? (Utf8)this.orgnr : null);
          break;

        case 3:
          this.servicecode = in.readString(this.servicecode instanceof Utf8 ? (Utf8)this.servicecode : null);
          break;

        case 4:
          this.serviceedition = in.readString(this.serviceedition instanceof Utf8 ? (Utf8)this.serviceedition : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










