/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.nav.arbeidsgiver.notifikasjon;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Beskjed extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3063913685974039761L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Beskjed\",\"namespace\":\"no.nav.arbeidsgiver.notifikasjon\",\"fields\":[{\"name\":\"synligFremTil\",\"type\":[\"null\",\"long\"],\"doc\":\"For hvor lenge beskjeden skal vises. Er den null, så er det ingen begrensning\",\"default\":null,\"logicalType\":\"timestamp-millis\"},{\"name\":\"tekst\",\"type\":\"string\",\"doc\":\"Teksten som presenteres til brukeren.\"},{\"name\":\"link\",\"type\":\"string\",\"doc\":\"Linken brukeren kan klikke på for å få mer informasjon om bedskjeden\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Beskjed> ENCODER =
      new BinaryMessageEncoder<Beskjed>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Beskjed> DECODER =
      new BinaryMessageDecoder<Beskjed>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Beskjed> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Beskjed> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Beskjed> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Beskjed>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Beskjed to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Beskjed from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Beskjed instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Beskjed fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** For hvor lenge beskjeden skal vises. Er den null, så er det ingen begrensning */
   private java.lang.Long synligFremTil;
  /** Teksten som presenteres til brukeren. */
   private java.lang.CharSequence tekst;
  /** Linken brukeren kan klikke på for å få mer informasjon om bedskjeden */
   private java.lang.CharSequence link;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Beskjed() {}

  /**
   * All-args constructor.
   * @param synligFremTil For hvor lenge beskjeden skal vises. Er den null, så er det ingen begrensning
   * @param tekst Teksten som presenteres til brukeren.
   * @param link Linken brukeren kan klikke på for å få mer informasjon om bedskjeden
   */
  public Beskjed(java.lang.Long synligFremTil, java.lang.CharSequence tekst, java.lang.CharSequence link) {
    this.synligFremTil = synligFremTil;
    this.tekst = tekst;
    this.link = link;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return synligFremTil;
    case 1: return tekst;
    case 2: return link;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: synligFremTil = (java.lang.Long)value$; break;
    case 1: tekst = (java.lang.CharSequence)value$; break;
    case 2: link = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'synligFremTil' field.
   * @return For hvor lenge beskjeden skal vises. Er den null, så er det ingen begrensning
   */
  public java.lang.Long getSynligFremTil() {
    return synligFremTil;
  }


  /**
   * Sets the value of the 'synligFremTil' field.
   * For hvor lenge beskjeden skal vises. Er den null, så er det ingen begrensning
   * @param value the value to set.
   */
  public void setSynligFremTil(java.lang.Long value) {
    this.synligFremTil = value;
  }

  /**
   * Gets the value of the 'tekst' field.
   * @return Teksten som presenteres til brukeren.
   */
  public java.lang.CharSequence getTekst() {
    return tekst;
  }


  /**
   * Sets the value of the 'tekst' field.
   * Teksten som presenteres til brukeren.
   * @param value the value to set.
   */
  public void setTekst(java.lang.CharSequence value) {
    this.tekst = value;
  }

  /**
   * Gets the value of the 'link' field.
   * @return Linken brukeren kan klikke på for å få mer informasjon om bedskjeden
   */
  public java.lang.CharSequence getLink() {
    return link;
  }


  /**
   * Sets the value of the 'link' field.
   * Linken brukeren kan klikke på for å få mer informasjon om bedskjeden
   * @param value the value to set.
   */
  public void setLink(java.lang.CharSequence value) {
    this.link = value;
  }

  /**
   * Creates a new Beskjed RecordBuilder.
   * @return A new Beskjed RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder newBuilder() {
    return new no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder();
  }

  /**
   * Creates a new Beskjed RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Beskjed RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder newBuilder(no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder other) {
    if (other == null) {
      return new no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder();
    } else {
      return new no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder(other);
    }
  }

  /**
   * Creates a new Beskjed RecordBuilder by copying an existing Beskjed instance.
   * @param other The existing instance to copy.
   * @return A new Beskjed RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder newBuilder(no.nav.arbeidsgiver.notifikasjon.Beskjed other) {
    if (other == null) {
      return new no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder();
    } else {
      return new no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder(other);
    }
  }

  /**
   * RecordBuilder for Beskjed instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Beskjed>
    implements org.apache.avro.data.RecordBuilder<Beskjed> {

    /** For hvor lenge beskjeden skal vises. Er den null, så er det ingen begrensning */
    private java.lang.Long synligFremTil;
    /** Teksten som presenteres til brukeren. */
    private java.lang.CharSequence tekst;
    /** Linken brukeren kan klikke på for å få mer informasjon om bedskjeden */
    private java.lang.CharSequence link;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.synligFremTil)) {
        this.synligFremTil = data().deepCopy(fields()[0].schema(), other.synligFremTil);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.tekst)) {
        this.tekst = data().deepCopy(fields()[1].schema(), other.tekst);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.link)) {
        this.link = data().deepCopy(fields()[2].schema(), other.link);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Beskjed instance
     * @param other The existing instance to copy.
     */
    private Builder(no.nav.arbeidsgiver.notifikasjon.Beskjed other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.synligFremTil)) {
        this.synligFremTil = data().deepCopy(fields()[0].schema(), other.synligFremTil);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tekst)) {
        this.tekst = data().deepCopy(fields()[1].schema(), other.tekst);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.link)) {
        this.link = data().deepCopy(fields()[2].schema(), other.link);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'synligFremTil' field.
      * For hvor lenge beskjeden skal vises. Er den null, så er det ingen begrensning
      * @return The value.
      */
    public java.lang.Long getSynligFremTil() {
      return synligFremTil;
    }


    /**
      * Sets the value of the 'synligFremTil' field.
      * For hvor lenge beskjeden skal vises. Er den null, så er det ingen begrensning
      * @param value The value of 'synligFremTil'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder setSynligFremTil(java.lang.Long value) {
      validate(fields()[0], value);
      this.synligFremTil = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'synligFremTil' field has been set.
      * For hvor lenge beskjeden skal vises. Er den null, så er det ingen begrensning
      * @return True if the 'synligFremTil' field has been set, false otherwise.
      */
    public boolean hasSynligFremTil() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'synligFremTil' field.
      * For hvor lenge beskjeden skal vises. Er den null, så er det ingen begrensning
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder clearSynligFremTil() {
      synligFremTil = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'tekst' field.
      * Teksten som presenteres til brukeren.
      * @return The value.
      */
    public java.lang.CharSequence getTekst() {
      return tekst;
    }


    /**
      * Sets the value of the 'tekst' field.
      * Teksten som presenteres til brukeren.
      * @param value The value of 'tekst'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder setTekst(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.tekst = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'tekst' field has been set.
      * Teksten som presenteres til brukeren.
      * @return True if the 'tekst' field has been set, false otherwise.
      */
    public boolean hasTekst() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'tekst' field.
      * Teksten som presenteres til brukeren.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder clearTekst() {
      tekst = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'link' field.
      * Linken brukeren kan klikke på for å få mer informasjon om bedskjeden
      * @return The value.
      */
    public java.lang.CharSequence getLink() {
      return link;
    }


    /**
      * Sets the value of the 'link' field.
      * Linken brukeren kan klikke på for å få mer informasjon om bedskjeden
      * @param value The value of 'link'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder setLink(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.link = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'link' field has been set.
      * Linken brukeren kan klikke på for å få mer informasjon om bedskjeden
      * @return True if the 'link' field has been set, false otherwise.
      */
    public boolean hasLink() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'link' field.
      * Linken brukeren kan klikke på for å få mer informasjon om bedskjeden
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Beskjed.Builder clearLink() {
      link = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Beskjed build() {
      try {
        Beskjed record = new Beskjed();
        record.synligFremTil = fieldSetFlags()[0] ? this.synligFremTil : (java.lang.Long) defaultValue(fields()[0]);
        record.tekst = fieldSetFlags()[1] ? this.tekst : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.link = fieldSetFlags()[2] ? this.link : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Beskjed>
    WRITER$ = (org.apache.avro.io.DatumWriter<Beskjed>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Beskjed>
    READER$ = (org.apache.avro.io.DatumReader<Beskjed>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.synligFremTil == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.synligFremTil);
    }

    out.writeString(this.tekst);

    out.writeString(this.link);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.synligFremTil = null;
      } else {
        this.synligFremTil = in.readLong();
      }

      this.tekst = in.readString(this.tekst instanceof Utf8 ? (Utf8)this.tekst : null);

      this.link = in.readString(this.link instanceof Utf8 ? (Utf8)this.link : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.synligFremTil = null;
          } else {
            this.synligFremTil = in.readLong();
          }
          break;

        case 1:
          this.tekst = in.readString(this.tekst instanceof Utf8 ? (Utf8)this.tekst : null);
          break;

        case 2:
          this.link = in.readString(this.link instanceof Utf8 ? (Utf8)this.link : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










