/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.nav.arbeidsgiver.notifikasjon;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Mottaker extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5465892660570550438L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Mottaker\",\"namespace\":\"no.nav.arbeidsgiver.notifikasjon\",\"fields\":[{\"name\":\"mottaker\",\"type\":[{\"type\":\"record\",\"name\":\"OrgnrFnr\",\"doc\":\"Mottas av dem med gitt fnr i konteksten av et bestemt orgnr\",\"fields\":[{\"name\":\"orgnr\",\"type\":\"string\"},{\"name\":\"fnr\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"OrgnrAltinnservice\",\"doc\":\"Mottas av alle som har tilgang til altinn-tjenesten i det gitte orgnr\",\"fields\":[{\"name\":\"orgnr\",\"type\":\"string\"},{\"name\":\"servicecode\",\"type\":\"string\"},{\"name\":\"serviceedition\",\"type\":\"string\"}]}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Mottaker> ENCODER =
      new BinaryMessageEncoder<Mottaker>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Mottaker> DECODER =
      new BinaryMessageDecoder<Mottaker>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Mottaker> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Mottaker> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Mottaker> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Mottaker>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Mottaker to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Mottaker from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Mottaker instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Mottaker fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Object mottaker;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Mottaker() {}

  /**
   * All-args constructor.
   * @param mottaker The new value for mottaker
   */
  public Mottaker(java.lang.Object mottaker) {
    this.mottaker = mottaker;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return mottaker;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: mottaker = value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'mottaker' field.
   * @return The value of the 'mottaker' field.
   */
  public java.lang.Object getMottaker() {
    return mottaker;
  }


  /**
   * Sets the value of the 'mottaker' field.
   * @param value the value to set.
   */
  public void setMottaker(java.lang.Object value) {
    this.mottaker = value;
  }

  /**
   * Creates a new Mottaker RecordBuilder.
   * @return A new Mottaker RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.Mottaker.Builder newBuilder() {
    return new no.nav.arbeidsgiver.notifikasjon.Mottaker.Builder();
  }

  /**
   * Creates a new Mottaker RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Mottaker RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.Mottaker.Builder newBuilder(no.nav.arbeidsgiver.notifikasjon.Mottaker.Builder other) {
    if (other == null) {
      return new no.nav.arbeidsgiver.notifikasjon.Mottaker.Builder();
    } else {
      return new no.nav.arbeidsgiver.notifikasjon.Mottaker.Builder(other);
    }
  }

  /**
   * Creates a new Mottaker RecordBuilder by copying an existing Mottaker instance.
   * @param other The existing instance to copy.
   * @return A new Mottaker RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.Mottaker.Builder newBuilder(no.nav.arbeidsgiver.notifikasjon.Mottaker other) {
    if (other == null) {
      return new no.nav.arbeidsgiver.notifikasjon.Mottaker.Builder();
    } else {
      return new no.nav.arbeidsgiver.notifikasjon.Mottaker.Builder(other);
    }
  }

  /**
   * RecordBuilder for Mottaker instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Mottaker>
    implements org.apache.avro.data.RecordBuilder<Mottaker> {

    private java.lang.Object mottaker;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.nav.arbeidsgiver.notifikasjon.Mottaker.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.mottaker)) {
        this.mottaker = data().deepCopy(fields()[0].schema(), other.mottaker);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Mottaker instance
     * @param other The existing instance to copy.
     */
    private Builder(no.nav.arbeidsgiver.notifikasjon.Mottaker other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.mottaker)) {
        this.mottaker = data().deepCopy(fields()[0].schema(), other.mottaker);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'mottaker' field.
      * @return The value.
      */
    public java.lang.Object getMottaker() {
      return mottaker;
    }


    /**
      * Sets the value of the 'mottaker' field.
      * @param value The value of 'mottaker'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Mottaker.Builder setMottaker(java.lang.Object value) {
      validate(fields()[0], value);
      this.mottaker = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'mottaker' field has been set.
      * @return True if the 'mottaker' field has been set, false otherwise.
      */
    public boolean hasMottaker() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'mottaker' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Mottaker.Builder clearMottaker() {
      mottaker = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Mottaker build() {
      try {
        Mottaker record = new Mottaker();
        record.mottaker = fieldSetFlags()[0] ? this.mottaker :  defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Mottaker>
    WRITER$ = (org.apache.avro.io.DatumWriter<Mottaker>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Mottaker>
    READER$ = (org.apache.avro.io.DatumReader<Mottaker>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










