/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.nav.arbeidsgiver.notifikasjon;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Nokkel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4368735184300408895L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Nokkel\",\"namespace\":\"no.nav.arbeidsgiver.notifikasjon\",\"fields\":[{\"name\":\"tjenestenavn\",\"type\":\"string\"},{\"name\":\"eventId\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Nokkel> ENCODER =
      new BinaryMessageEncoder<Nokkel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Nokkel> DECODER =
      new BinaryMessageDecoder<Nokkel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Nokkel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Nokkel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Nokkel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Nokkel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Nokkel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Nokkel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Nokkel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Nokkel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence tjenestenavn;
   private java.lang.CharSequence eventId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Nokkel() {}

  /**
   * All-args constructor.
   * @param tjenestenavn The new value for tjenestenavn
   * @param eventId The new value for eventId
   */
  public Nokkel(java.lang.CharSequence tjenestenavn, java.lang.CharSequence eventId) {
    this.tjenestenavn = tjenestenavn;
    this.eventId = eventId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tjenestenavn;
    case 1: return eventId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tjenestenavn = (java.lang.CharSequence)value$; break;
    case 1: eventId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'tjenestenavn' field.
   * @return The value of the 'tjenestenavn' field.
   */
  public java.lang.CharSequence getTjenestenavn() {
    return tjenestenavn;
  }


  /**
   * Sets the value of the 'tjenestenavn' field.
   * @param value the value to set.
   */
  public void setTjenestenavn(java.lang.CharSequence value) {
    this.tjenestenavn = value;
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Creates a new Nokkel RecordBuilder.
   * @return A new Nokkel RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder newBuilder() {
    return new no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder();
  }

  /**
   * Creates a new Nokkel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Nokkel RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder newBuilder(no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder other) {
    if (other == null) {
      return new no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder();
    } else {
      return new no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder(other);
    }
  }

  /**
   * Creates a new Nokkel RecordBuilder by copying an existing Nokkel instance.
   * @param other The existing instance to copy.
   * @return A new Nokkel RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder newBuilder(no.nav.arbeidsgiver.notifikasjon.Nokkel other) {
    if (other == null) {
      return new no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder();
    } else {
      return new no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder(other);
    }
  }

  /**
   * RecordBuilder for Nokkel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Nokkel>
    implements org.apache.avro.data.RecordBuilder<Nokkel> {

    private java.lang.CharSequence tjenestenavn;
    private java.lang.CharSequence eventId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tjenestenavn)) {
        this.tjenestenavn = data().deepCopy(fields()[0].schema(), other.tjenestenavn);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.eventId)) {
        this.eventId = data().deepCopy(fields()[1].schema(), other.eventId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Nokkel instance
     * @param other The existing instance to copy.
     */
    private Builder(no.nav.arbeidsgiver.notifikasjon.Nokkel other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.tjenestenavn)) {
        this.tjenestenavn = data().deepCopy(fields()[0].schema(), other.tjenestenavn);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventId)) {
        this.eventId = data().deepCopy(fields()[1].schema(), other.eventId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'tjenestenavn' field.
      * @return The value.
      */
    public java.lang.CharSequence getTjenestenavn() {
      return tjenestenavn;
    }


    /**
      * Sets the value of the 'tjenestenavn' field.
      * @param value The value of 'tjenestenavn'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder setTjenestenavn(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tjenestenavn = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tjenestenavn' field has been set.
      * @return True if the 'tjenestenavn' field has been set, false otherwise.
      */
    public boolean hasTjenestenavn() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tjenestenavn' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder clearTjenestenavn() {
      tjenestenavn = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.eventId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Nokkel.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Nokkel build() {
      try {
        Nokkel record = new Nokkel();
        record.tjenestenavn = fieldSetFlags()[0] ? this.tjenestenavn : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.eventId = fieldSetFlags()[1] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Nokkel>
    WRITER$ = (org.apache.avro.io.DatumWriter<Nokkel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Nokkel>
    READER$ = (org.apache.avro.io.DatumReader<Nokkel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.tjenestenavn);

    out.writeString(this.eventId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.tjenestenavn = in.readString(this.tjenestenavn instanceof Utf8 ? (Utf8)this.tjenestenavn : null);

      this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.tjenestenavn = in.readString(this.tjenestenavn instanceof Utf8 ? (Utf8)this.tjenestenavn : null);
          break;

        case 1:
          this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










