/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.nav.arbeidsgiver.notifikasjon;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Oppgave extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1855378467760842440L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Oppgave\",\"namespace\":\"no.nav.arbeidsgiver.notifikasjon\",\"fields\":[{\"name\":\"tidspunkt\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"fodselsnummer\",\"type\":\"string\"},{\"name\":\"grupperingsId\",\"type\":\"string\"},{\"name\":\"tekst\",\"type\":\"string\"},{\"name\":\"link\",\"type\":\"string\"},{\"name\":\"sikkerhetsnivaa\",\"type\":\"int\",\"default\":4}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Oppgave> ENCODER =
      new BinaryMessageEncoder<Oppgave>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Oppgave> DECODER =
      new BinaryMessageDecoder<Oppgave>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Oppgave> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Oppgave> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Oppgave> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Oppgave>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Oppgave to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Oppgave from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Oppgave instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Oppgave fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long tidspunkt;
   private java.lang.CharSequence fodselsnummer;
   private java.lang.CharSequence grupperingsId;
   private java.lang.CharSequence tekst;
   private java.lang.CharSequence link;
   private int sikkerhetsnivaa;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Oppgave() {}

  /**
   * All-args constructor.
   * @param tidspunkt The new value for tidspunkt
   * @param fodselsnummer The new value for fodselsnummer
   * @param grupperingsId The new value for grupperingsId
   * @param tekst The new value for tekst
   * @param link The new value for link
   * @param sikkerhetsnivaa The new value for sikkerhetsnivaa
   */
  public Oppgave(java.lang.Long tidspunkt, java.lang.CharSequence fodselsnummer, java.lang.CharSequence grupperingsId, java.lang.CharSequence tekst, java.lang.CharSequence link, java.lang.Integer sikkerhetsnivaa) {
    this.tidspunkt = tidspunkt;
    this.fodselsnummer = fodselsnummer;
    this.grupperingsId = grupperingsId;
    this.tekst = tekst;
    this.link = link;
    this.sikkerhetsnivaa = sikkerhetsnivaa;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tidspunkt;
    case 1: return fodselsnummer;
    case 2: return grupperingsId;
    case 3: return tekst;
    case 4: return link;
    case 5: return sikkerhetsnivaa;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tidspunkt = (java.lang.Long)value$; break;
    case 1: fodselsnummer = (java.lang.CharSequence)value$; break;
    case 2: grupperingsId = (java.lang.CharSequence)value$; break;
    case 3: tekst = (java.lang.CharSequence)value$; break;
    case 4: link = (java.lang.CharSequence)value$; break;
    case 5: sikkerhetsnivaa = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'tidspunkt' field.
   * @return The value of the 'tidspunkt' field.
   */
  public long getTidspunkt() {
    return tidspunkt;
  }


  /**
   * Sets the value of the 'tidspunkt' field.
   * @param value the value to set.
   */
  public void setTidspunkt(long value) {
    this.tidspunkt = value;
  }

  /**
   * Gets the value of the 'fodselsnummer' field.
   * @return The value of the 'fodselsnummer' field.
   */
  public java.lang.CharSequence getFodselsnummer() {
    return fodselsnummer;
  }


  /**
   * Sets the value of the 'fodselsnummer' field.
   * @param value the value to set.
   */
  public void setFodselsnummer(java.lang.CharSequence value) {
    this.fodselsnummer = value;
  }

  /**
   * Gets the value of the 'grupperingsId' field.
   * @return The value of the 'grupperingsId' field.
   */
  public java.lang.CharSequence getGrupperingsId() {
    return grupperingsId;
  }


  /**
   * Sets the value of the 'grupperingsId' field.
   * @param value the value to set.
   */
  public void setGrupperingsId(java.lang.CharSequence value) {
    this.grupperingsId = value;
  }

  /**
   * Gets the value of the 'tekst' field.
   * @return The value of the 'tekst' field.
   */
  public java.lang.CharSequence getTekst() {
    return tekst;
  }


  /**
   * Sets the value of the 'tekst' field.
   * @param value the value to set.
   */
  public void setTekst(java.lang.CharSequence value) {
    this.tekst = value;
  }

  /**
   * Gets the value of the 'link' field.
   * @return The value of the 'link' field.
   */
  public java.lang.CharSequence getLink() {
    return link;
  }


  /**
   * Sets the value of the 'link' field.
   * @param value the value to set.
   */
  public void setLink(java.lang.CharSequence value) {
    this.link = value;
  }

  /**
   * Gets the value of the 'sikkerhetsnivaa' field.
   * @return The value of the 'sikkerhetsnivaa' field.
   */
  public int getSikkerhetsnivaa() {
    return sikkerhetsnivaa;
  }


  /**
   * Sets the value of the 'sikkerhetsnivaa' field.
   * @param value the value to set.
   */
  public void setSikkerhetsnivaa(int value) {
    this.sikkerhetsnivaa = value;
  }

  /**
   * Creates a new Oppgave RecordBuilder.
   * @return A new Oppgave RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder newBuilder() {
    return new no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder();
  }

  /**
   * Creates a new Oppgave RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Oppgave RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder newBuilder(no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder other) {
    if (other == null) {
      return new no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder();
    } else {
      return new no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder(other);
    }
  }

  /**
   * Creates a new Oppgave RecordBuilder by copying an existing Oppgave instance.
   * @param other The existing instance to copy.
   * @return A new Oppgave RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder newBuilder(no.nav.arbeidsgiver.notifikasjon.Oppgave other) {
    if (other == null) {
      return new no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder();
    } else {
      return new no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder(other);
    }
  }

  /**
   * RecordBuilder for Oppgave instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Oppgave>
    implements org.apache.avro.data.RecordBuilder<Oppgave> {

    private long tidspunkt;
    private java.lang.CharSequence fodselsnummer;
    private java.lang.CharSequence grupperingsId;
    private java.lang.CharSequence tekst;
    private java.lang.CharSequence link;
    private int sikkerhetsnivaa;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tidspunkt)) {
        this.tidspunkt = data().deepCopy(fields()[0].schema(), other.tidspunkt);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.fodselsnummer)) {
        this.fodselsnummer = data().deepCopy(fields()[1].schema(), other.fodselsnummer);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.grupperingsId)) {
        this.grupperingsId = data().deepCopy(fields()[2].schema(), other.grupperingsId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.tekst)) {
        this.tekst = data().deepCopy(fields()[3].schema(), other.tekst);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.link)) {
        this.link = data().deepCopy(fields()[4].schema(), other.link);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.sikkerhetsnivaa)) {
        this.sikkerhetsnivaa = data().deepCopy(fields()[5].schema(), other.sikkerhetsnivaa);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Oppgave instance
     * @param other The existing instance to copy.
     */
    private Builder(no.nav.arbeidsgiver.notifikasjon.Oppgave other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.tidspunkt)) {
        this.tidspunkt = data().deepCopy(fields()[0].schema(), other.tidspunkt);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fodselsnummer)) {
        this.fodselsnummer = data().deepCopy(fields()[1].schema(), other.fodselsnummer);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.grupperingsId)) {
        this.grupperingsId = data().deepCopy(fields()[2].schema(), other.grupperingsId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.tekst)) {
        this.tekst = data().deepCopy(fields()[3].schema(), other.tekst);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.link)) {
        this.link = data().deepCopy(fields()[4].schema(), other.link);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.sikkerhetsnivaa)) {
        this.sikkerhetsnivaa = data().deepCopy(fields()[5].schema(), other.sikkerhetsnivaa);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'tidspunkt' field.
      * @return The value.
      */
    public long getTidspunkt() {
      return tidspunkt;
    }


    /**
      * Sets the value of the 'tidspunkt' field.
      * @param value The value of 'tidspunkt'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder setTidspunkt(long value) {
      validate(fields()[0], value);
      this.tidspunkt = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tidspunkt' field has been set.
      * @return True if the 'tidspunkt' field has been set, false otherwise.
      */
    public boolean hasTidspunkt() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tidspunkt' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder clearTidspunkt() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'fodselsnummer' field.
      * @return The value.
      */
    public java.lang.CharSequence getFodselsnummer() {
      return fodselsnummer;
    }


    /**
      * Sets the value of the 'fodselsnummer' field.
      * @param value The value of 'fodselsnummer'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder setFodselsnummer(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.fodselsnummer = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'fodselsnummer' field has been set.
      * @return True if the 'fodselsnummer' field has been set, false otherwise.
      */
    public boolean hasFodselsnummer() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'fodselsnummer' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder clearFodselsnummer() {
      fodselsnummer = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'grupperingsId' field.
      * @return The value.
      */
    public java.lang.CharSequence getGrupperingsId() {
      return grupperingsId;
    }


    /**
      * Sets the value of the 'grupperingsId' field.
      * @param value The value of 'grupperingsId'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder setGrupperingsId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.grupperingsId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'grupperingsId' field has been set.
      * @return True if the 'grupperingsId' field has been set, false otherwise.
      */
    public boolean hasGrupperingsId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'grupperingsId' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder clearGrupperingsId() {
      grupperingsId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'tekst' field.
      * @return The value.
      */
    public java.lang.CharSequence getTekst() {
      return tekst;
    }


    /**
      * Sets the value of the 'tekst' field.
      * @param value The value of 'tekst'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder setTekst(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.tekst = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'tekst' field has been set.
      * @return True if the 'tekst' field has been set, false otherwise.
      */
    public boolean hasTekst() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'tekst' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder clearTekst() {
      tekst = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'link' field.
      * @return The value.
      */
    public java.lang.CharSequence getLink() {
      return link;
    }


    /**
      * Sets the value of the 'link' field.
      * @param value The value of 'link'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder setLink(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.link = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'link' field has been set.
      * @return True if the 'link' field has been set, false otherwise.
      */
    public boolean hasLink() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'link' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder clearLink() {
      link = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'sikkerhetsnivaa' field.
      * @return The value.
      */
    public int getSikkerhetsnivaa() {
      return sikkerhetsnivaa;
    }


    /**
      * Sets the value of the 'sikkerhetsnivaa' field.
      * @param value The value of 'sikkerhetsnivaa'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder setSikkerhetsnivaa(int value) {
      validate(fields()[5], value);
      this.sikkerhetsnivaa = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'sikkerhetsnivaa' field has been set.
      * @return True if the 'sikkerhetsnivaa' field has been set, false otherwise.
      */
    public boolean hasSikkerhetsnivaa() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'sikkerhetsnivaa' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.Oppgave.Builder clearSikkerhetsnivaa() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Oppgave build() {
      try {
        Oppgave record = new Oppgave();
        record.tidspunkt = fieldSetFlags()[0] ? this.tidspunkt : (java.lang.Long) defaultValue(fields()[0]);
        record.fodselsnummer = fieldSetFlags()[1] ? this.fodselsnummer : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.grupperingsId = fieldSetFlags()[2] ? this.grupperingsId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.tekst = fieldSetFlags()[3] ? this.tekst : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.link = fieldSetFlags()[4] ? this.link : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.sikkerhetsnivaa = fieldSetFlags()[5] ? this.sikkerhetsnivaa : (java.lang.Integer) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Oppgave>
    WRITER$ = (org.apache.avro.io.DatumWriter<Oppgave>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Oppgave>
    READER$ = (org.apache.avro.io.DatumReader<Oppgave>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.tidspunkt);

    out.writeString(this.fodselsnummer);

    out.writeString(this.grupperingsId);

    out.writeString(this.tekst);

    out.writeString(this.link);

    out.writeInt(this.sikkerhetsnivaa);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.tidspunkt = in.readLong();

      this.fodselsnummer = in.readString(this.fodselsnummer instanceof Utf8 ? (Utf8)this.fodselsnummer : null);

      this.grupperingsId = in.readString(this.grupperingsId instanceof Utf8 ? (Utf8)this.grupperingsId : null);

      this.tekst = in.readString(this.tekst instanceof Utf8 ? (Utf8)this.tekst : null);

      this.link = in.readString(this.link instanceof Utf8 ? (Utf8)this.link : null);

      this.sikkerhetsnivaa = in.readInt();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.tidspunkt = in.readLong();
          break;

        case 1:
          this.fodselsnummer = in.readString(this.fodselsnummer instanceof Utf8 ? (Utf8)this.fodselsnummer : null);
          break;

        case 2:
          this.grupperingsId = in.readString(this.grupperingsId instanceof Utf8 ? (Utf8)this.grupperingsId : null);
          break;

        case 3:
          this.tekst = in.readString(this.tekst instanceof Utf8 ? (Utf8)this.tekst : null);
          break;

        case 4:
          this.link = in.readString(this.link instanceof Utf8 ? (Utf8)this.link : null);
          break;

        case 5:
          this.sikkerhetsnivaa = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










