/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.nav.arbeidsgiver.notifikasjon;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Mottas av alle som har tilgang til altinn-tjenesten i det gitte orgnr */
@org.apache.avro.specific.AvroGenerated
public class OrgnrAltinnservice extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1040206206274510349L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrgnrAltinnservice\",\"namespace\":\"no.nav.arbeidsgiver.notifikasjon\",\"doc\":\"Mottas av alle som har tilgang til altinn-tjenesten i det gitte orgnr\",\"fields\":[{\"name\":\"orgnr\",\"type\":\"string\"},{\"name\":\"servicecode\",\"type\":\"string\"},{\"name\":\"serviceedition\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrgnrAltinnservice> ENCODER =
      new BinaryMessageEncoder<OrgnrAltinnservice>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrgnrAltinnservice> DECODER =
      new BinaryMessageDecoder<OrgnrAltinnservice>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrgnrAltinnservice> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrgnrAltinnservice> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrgnrAltinnservice> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrgnrAltinnservice>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrgnrAltinnservice to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrgnrAltinnservice from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrgnrAltinnservice instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrgnrAltinnservice fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence orgnr;
   private java.lang.CharSequence servicecode;
   private java.lang.CharSequence serviceedition;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrgnrAltinnservice() {}

  /**
   * All-args constructor.
   * @param orgnr The new value for orgnr
   * @param servicecode The new value for servicecode
   * @param serviceedition The new value for serviceedition
   */
  public OrgnrAltinnservice(java.lang.CharSequence orgnr, java.lang.CharSequence servicecode, java.lang.CharSequence serviceedition) {
    this.orgnr = orgnr;
    this.servicecode = servicecode;
    this.serviceedition = serviceedition;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orgnr;
    case 1: return servicecode;
    case 2: return serviceedition;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orgnr = (java.lang.CharSequence)value$; break;
    case 1: servicecode = (java.lang.CharSequence)value$; break;
    case 2: serviceedition = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orgnr' field.
   * @return The value of the 'orgnr' field.
   */
  public java.lang.CharSequence getOrgnr() {
    return orgnr;
  }


  /**
   * Sets the value of the 'orgnr' field.
   * @param value the value to set.
   */
  public void setOrgnr(java.lang.CharSequence value) {
    this.orgnr = value;
  }

  /**
   * Gets the value of the 'servicecode' field.
   * @return The value of the 'servicecode' field.
   */
  public java.lang.CharSequence getServicecode() {
    return servicecode;
  }


  /**
   * Sets the value of the 'servicecode' field.
   * @param value the value to set.
   */
  public void setServicecode(java.lang.CharSequence value) {
    this.servicecode = value;
  }

  /**
   * Gets the value of the 'serviceedition' field.
   * @return The value of the 'serviceedition' field.
   */
  public java.lang.CharSequence getServiceedition() {
    return serviceedition;
  }


  /**
   * Sets the value of the 'serviceedition' field.
   * @param value the value to set.
   */
  public void setServiceedition(java.lang.CharSequence value) {
    this.serviceedition = value;
  }

  /**
   * Creates a new OrgnrAltinnservice RecordBuilder.
   * @return A new OrgnrAltinnservice RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder newBuilder() {
    return new no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder();
  }

  /**
   * Creates a new OrgnrAltinnservice RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrgnrAltinnservice RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder newBuilder(no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder other) {
    if (other == null) {
      return new no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder();
    } else {
      return new no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder(other);
    }
  }

  /**
   * Creates a new OrgnrAltinnservice RecordBuilder by copying an existing OrgnrAltinnservice instance.
   * @param other The existing instance to copy.
   * @return A new OrgnrAltinnservice RecordBuilder
   */
  public static no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder newBuilder(no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice other) {
    if (other == null) {
      return new no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder();
    } else {
      return new no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrgnrAltinnservice instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrgnrAltinnservice>
    implements org.apache.avro.data.RecordBuilder<OrgnrAltinnservice> {

    private java.lang.CharSequence orgnr;
    private java.lang.CharSequence servicecode;
    private java.lang.CharSequence serviceedition;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orgnr)) {
        this.orgnr = data().deepCopy(fields()[0].schema(), other.orgnr);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.servicecode)) {
        this.servicecode = data().deepCopy(fields()[1].schema(), other.servicecode);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.serviceedition)) {
        this.serviceedition = data().deepCopy(fields()[2].schema(), other.serviceedition);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing OrgnrAltinnservice instance
     * @param other The existing instance to copy.
     */
    private Builder(no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.orgnr)) {
        this.orgnr = data().deepCopy(fields()[0].schema(), other.orgnr);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.servicecode)) {
        this.servicecode = data().deepCopy(fields()[1].schema(), other.servicecode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.serviceedition)) {
        this.serviceedition = data().deepCopy(fields()[2].schema(), other.serviceedition);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'orgnr' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrgnr() {
      return orgnr;
    }


    /**
      * Sets the value of the 'orgnr' field.
      * @param value The value of 'orgnr'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder setOrgnr(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.orgnr = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orgnr' field has been set.
      * @return True if the 'orgnr' field has been set, false otherwise.
      */
    public boolean hasOrgnr() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orgnr' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder clearOrgnr() {
      orgnr = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'servicecode' field.
      * @return The value.
      */
    public java.lang.CharSequence getServicecode() {
      return servicecode;
    }


    /**
      * Sets the value of the 'servicecode' field.
      * @param value The value of 'servicecode'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder setServicecode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.servicecode = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'servicecode' field has been set.
      * @return True if the 'servicecode' field has been set, false otherwise.
      */
    public boolean hasServicecode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'servicecode' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder clearServicecode() {
      servicecode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'serviceedition' field.
      * @return The value.
      */
    public java.lang.CharSequence getServiceedition() {
      return serviceedition;
    }


    /**
      * Sets the value of the 'serviceedition' field.
      * @param value The value of 'serviceedition'.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder setServiceedition(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.serviceedition = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'serviceedition' field has been set.
      * @return True if the 'serviceedition' field has been set, false otherwise.
      */
    public boolean hasServiceedition() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'serviceedition' field.
      * @return This builder.
      */
    public no.nav.arbeidsgiver.notifikasjon.OrgnrAltinnservice.Builder clearServiceedition() {
      serviceedition = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrgnrAltinnservice build() {
      try {
        OrgnrAltinnservice record = new OrgnrAltinnservice();
        record.orgnr = fieldSetFlags()[0] ? this.orgnr : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.servicecode = fieldSetFlags()[1] ? this.servicecode : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.serviceedition = fieldSetFlags()[2] ? this.serviceedition : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrgnrAltinnservice>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrgnrAltinnservice>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrgnrAltinnservice>
    READER$ = (org.apache.avro.io.DatumReader<OrgnrAltinnservice>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.orgnr);

    out.writeString(this.servicecode);

    out.writeString(this.serviceedition);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.orgnr = in.readString(this.orgnr instanceof Utf8 ? (Utf8)this.orgnr : null);

      this.servicecode = in.readString(this.servicecode instanceof Utf8 ? (Utf8)this.servicecode : null);

      this.serviceedition = in.readString(this.serviceedition instanceof Utf8 ? (Utf8)this.serviceedition : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.orgnr = in.readString(this.orgnr instanceof Utf8 ? (Utf8)this.orgnr : null);
          break;

        case 1:
          this.servicecode = in.readString(this.servicecode instanceof Utf8 ? (Utf8)this.servicecode : null);
          break;

        case 2:
          this.serviceedition = in.readString(this.serviceedition instanceof Utf8 ? (Utf8)this.serviceedition : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










