apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: mockproducer
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  team: arbeidsgiver
  liveness:
    path: /liveness
  readiness:
    path: /readiness
  kafka:
    pool: nav-dev
  external:
    - host: nav-dev-kafka-nav-dev.aivencloud.com
      ports:
        - port: 26487
          protocol: TCP
