apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjoner-mock-producer
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
    notifikasjoner: ja

spec:
  image: {{ image }}
  team: arbeidsgiver
  liveness:
    path: /liveness
  readiness:
    path: /readiness
  kafka:
    pool: nav-dev
