apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: arbeidsgiver-notifikasjon
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete, compact
    minimumInSyncReplicas: 1
    retentionBytes: -1
    retentionHours: -1
  acl:
    - team: arbeidsgiver
      application: mockproducer
      access: readwrite
