apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: notifikasjoner
  annotations:
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  pool: nav-dev
  config:
    minimumInSyncReplicas: 1
    retentionBytes: -1
    retentionHours: -1
  acl:
    - team: arbeidsgiver
      application: mockproducer
      access: readwrite
    - team: arbeidsgiver
      application: notifikasjon-frontend-api
      access: read
