name: Bygg og deploy mock-producer

on:
  push:
    branches: ['main']
    paths: ['avro-skjema/**', 'mock-producer/**']
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}-mock-producer
  IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}-mock-producer:${{ github.sha }}
  undermappe: mock-producer

jobs:
  bygg:
    name: Bygg
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - name: Hent tag
        run: echo "TAG=$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)">>$GITHUB_ENV

      - name: Oppsett Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gjenopprett Maven-cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Bygg og test med Maven
        run: mvn -B -pl ${{ env.undermappe }} -am clean test package
        env:
          GITHUB_USERNAME: x-access-token

      - name: Bygg, tag og push Docker-image
        working-directory: ${{ env.undermappe }}
        run: |
          docker build --tag $IMAGE --tag $IMAGE_BASE:latest .
          echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u $GITHUB_REPOSITORY --password-stdin
          docker push $IMAGE_BASE

  deploy-dev:
    name: Deploy til dev
    runs-on: ubuntu-latest
    needs: bygg
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: ./${{ env.undermappe }}/nais/dev-gcp.yaml
          PRINT_PAYLOAD: true

 # deploy-prod:
 #    name: Deploy til prod
 #   runs-on: ubuntu-latest
 #   needs: deploy-dev
 #   steps:
 #     - name: Sjekk ut kode
 #       uses: actions/checkout@v2
 #     - name: Deploy til prod-fss
 #       uses: nais/deploy/actions/deploy@v1
 #       env:
 #         APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
 #         CLUSTER: prod-fss
 #         RESOURCE: nais/prod.yaml
 #         PRINT_PAYLOAD: true
